#!/usr/bin/with-contenv bash
# shellcheck shell=bash

# make our folders
mkdir -p \
    /var/run/dbus \
    /run/dbus \
    /config/dbase_and_logs \
    /daapd-pidfolder


if [[ -e /var/run/dbus.pid ]]; then
    rm -f /var/run/dbus.pid
fi

if [[ -e /run/dbus/dbus.pid ]]; then
    rm -f /run/dbus/dbus.pid
fi

dbus-uuidgen --ensure
sleep 1

# configure defaults copy of conf
if [[ ! -e "/defaults/owntone.conf" ]]; then
cp /etc/owntone.conf.orig /defaults/owntone.conf
sed -i \
    -e '/cache_path\ =/ s/# *//' \
    -e '/db_path\ =/ s/# *//' \
    -e s#ipv6\ =\ yes#ipv6\ =\ no#g \
    -e s#My\ Music\ on\ %h#LS.IO\ Music#g \
    -e s#/srv/music#/music#g \
    -e 's/\(uid.*=\).*/\1 \"abc\"/g' \
    -e s#/var/cache/owntone/cache.db#/config/dbase_and_logs/cache.db#g \
    -e s#/var/cache/owntone/songs3.db#/config/dbase_and_logs/songs3.db#g \
    -e s#/var/log/owntone.log#/config/dbase_and_logs/owntone.log#g \
    -e '/trusted_networks\ =/ s/# *//' \
    -e 's#trusted_networks = {.*#trusted_networks = { "lan" }#' \
    -e '/admin_password\ =/ s/# *//' \
    -e 's#admin_password = .*#admin_password = "changeme"#' \
    /defaults/owntone.conf
fi

# symlink conf to /conf
if [[ ! -f /config/owntone.conf ]]; then
    cp /defaults/owntone.conf /config/owntone.conf
fi

if [[ ! -L /etc/owntone.conf && -f /etc/owntone.conf ]]; then
    rm /etc/owntone.conf
fi

if [[ ! -L /etc/owntone.conf ]]; then
    ln -s /config/owntone.conf /etc/owntone.conf
fi

# permissions
lsiown -R abc:abc \
    /app \
    /config \
    /daapd-pidfolder

