#!/usr/bin/with-contenv bash

# make folders
mkdir -p \
	/config/dbase_and_logs \
	/daapd-pidfolder

# configure defaults copy of conf
if [ ! -e "/defaults/forked-daapd.conf" ]; then
cp /etc/forked-daapd.conf.orig /defaults/forked-daapd.conf
sed -i \
	-e "/cache_path\ =/ s/# *//" \
	-e "/db_path\ =/ s/# *//" \
	-e s#ipv6\ =\ yes#ipv6\ =\ no#g \
	-e s#My\ Music\ on\ %h#LS.IO\ Music#g \
	-e s#/srv/music#/music#g \
	-e 's/\(uid.*=\).*/\1 \"abc\"/g' \
	-e s#/var/cache/forked-daapd/cache.db#/config/dbase_and_logs/cache.db#g \
	-e s#/var/cache/forked-daapd/songs3.db#/config/dbase_and_logs/songs3.db#g \
	-e s#/var/log/forked-daapd.log#/config/dbase_and_logs/forked-daapd.log#g \
 /defaults/forked-daapd.conf
fi

# symlink conf to /conf
[[ ! -f /config/forked-daapd.conf ]] && \
	cp /defaults/forked-daapd.conf /config/forked-daapd.conf
[[ ! -L /etc/forked-daapd.conf && -f /etc/forked-daapd.conf ]] && \
	rm /etc/forked-daapd.conf
[[ ! -L /etc/forked-daapd.conf ]] && \
	ln -s /config/forked-daapd.conf /etc/forked-daapd.conf


# permissions
chown -R abc:abc \
	/app \
	/config \
	/daapd-pidfolder
